services:
    tailscale:
        authKey: ENC[AES256_GCM,data:SPCOTnGixcXJ6iCEfCvNmb3t93ea51cZiiuI57C4JZCqJzcmOY2hxv9FvIlSZ4mKqKnZL8BsvGS8SoEpavc=,iv:HmHZs45/mA06LqvCbvCUWBDyCBfY/Cojgaqg1lEZk1E=,tag:jeIUqeIR214hK3gUHKfn3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dGlQOFcrMGllbFFQbDVk
            YmplVGZqczgraUYxckJqMXA5K09GeGc4OEdFCkFBdEczM0RDMDFjNTh2NHY4dU4z
            d01LZTQ2QXJyUkxMR1YvUVZBanEwZlkKLS0tIERweDBYTm14d3BlNm9iems2SjZn
            NjcvSGl5dnBkbG9qYXZ5c1BYMUgzdEEKsauQGDAEBor3Lg62eCDWaVpSSvvfrtWG
            pd+xecmbvcRUFpbqGAusKHxePj6je4cxxsaMP4V5fE662LZ9EMzy3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132zjthznrrjejt2kawgmu3cj33jt65vv0c5tg7vshknnshucrylsdaty4t
    lastmodified: "2026-09-29T16:08:30Z"
    mac: ENC[AES256_GCM,data:sfz4uK7X5tWpAy90w1APzKmbP1bDmbusqgSf43bUTjx0Pbl8JjV1obY25eIHuykUKXlDXb4E5G7M9AmlYpnq14wnbqMlVxLFmmSd5CQZyM2116/urRR7hDcOEGk2TF9YjYKpRrJij7GdaQiBFCnLxYCRNg2VWEwgmeeflWEYcGU=,iv:xrWEGT/L2J1xQrJy26ffyjz4CfvZM4AvLiKv6/vT6o4=,tag:m2wAa5djeDlXJ8NlzH4jYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
