services:
    caddy:
        cloudflare_dns_api_token: ENC[AES256_GCM,data:lNB+WZvCq2DLBmDnribrF3oLiEfQaknMxJ2tt9aDRE1LZckPNqmFwIV0RRgInt7h5T3OpEgEh0N8D/8lFiRCOrJO/kLJuxio0hdDZZ8/Eg==,iv:zEjsQjkX4V6fqGrHLuok3uTBnhV52rGleZnpNvPcWsA=,tag:8jwV2PGSRUyKpFRlvzDEcg==,type:str]
    tailscale:
        authKey: ENC[AES256_GCM,data:SPCOTnGixcXJ6iCEfCvNmb3t93ea51cZiiuI57C4JZCqJzcmOY2hxv9FvIlSZ4mKqKnZL8BsvGS8SoEpavc=,iv:HmHZs45/mA06LqvCbvCUWBDyCBfY/Cojgaqg1lEZk1E=,tag:jeIUqeIR214hK3gUHKfn3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dGlQOFcrMGllbFFQbDVk
            YmplVGZqczgraUYxckJqMXA5K09GeGc4OEdFCkFBdEczM0RDMDFjNTh2NHY4dU4z
            d01LZTQ2QXJyUkxMR1YvUVZBanEwZlkKLS0tIERweDBYTm14d3BlNm9iems2SjZn
            NjcvSGl5dnBkbG9qYXZ5c1BYMUgzdEEKsauQGDAEBor3Lg62eCDWaVpSSvvfrtWG
            pd+xecmbvcRUFpbqGAusKHxePj6je4cxxsaMP4V5fE662LZ9EMzy3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132zjthznrrjejt2kawgmu3cj33jt65vv0c5tg7vshknnshucrylsdaty4t
    lastmodified: "2026-09-30T09:27:19Z"
    mac: ENC[AES256_GCM,data:Hlrqf9A4U5+OUMjOl5zBuJ3q4zb0xBStOgODhMxTJ/f0ChmNUORJ0o63pB4jwfdmZowreDJIeVUMYCPpKjc6OsCAj5XJce6Kd1Ezh+jjw7AeNcDW3QJrSQ1ubeU68HbvOTsLikf1ryIGlmXQvuRK0tu8A6/t10XDE2Q3fjSnXow=,iv:N5w4B7DtbBOpNbMT48g/1/u6YiHAHmr/aB6ftr2GvHs=,tag:dawjFnHDyEjFmqFnlDDQBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
