name: kanbn
services:
  migrate:
    image: ghcr.io/kanbn/kan-migrate:0.6.0
    user: "kanbn:kanbn"
    environment:
      POSTGRES_URL: postgresql://kanbn@/kanbn?host=/var/run/postgresql
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    restart: "no"

  web:
    image: ghcr.io/kanbn/kan:0.6.0
    environment:
      POSTGRES_URL: postgresql://kanbn@/kanbn?host=/var/run/postgresql
    user: "kanbn"
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - 127.0.0.0:3345:3000
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
