# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."kanbn-migrate" = {
    image = "ghcr.io/kanbn/kan-migrate:0.6.0";
    environment = {
      "POSTGRES_URL" = "postgresql://kanbn@/kanbn?host=/var/run/postgresql";
    };
    volumes = [
      "/etc/group:/etc/group:ro"
      "/etc/passwd:/etc/passwd:ro"
      "/var/run/postgresql:/var/run/postgresql:rw"
    ];
    user = "kanbn:kanbn";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=migrate"
      "--network=kanbn_default"
    ];
  };
  systemd.services."podman-kanbn-migrate" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-kanbn_default.service"
    ];
    requires = [
      "podman-network-kanbn_default.service"
    ];
    partOf = [
      "podman-compose-kanbn-root.target"
    ];
    wantedBy = [
      "podman-compose-kanbn-root.target"
    ];
  };
  virtualisation.oci-containers.containers."kanbn-web" = {
    image = "ghcr.io/kanbn/kan:0.6.0";
    environment = {
      "POSTGRES_URL" = "postgresql://kanbn@/kanbn?host=/var/run/postgresql";
    };
    volumes = [
      "/etc/group:/etc/group:ro"
      "/etc/passwd:/etc/passwd:ro"
      "/var/run/postgresql:/var/run/postgresql:rw"
    ];
    ports = [
      "127.0.0.0:3345:3000/tcp"
    ];
    dependsOn = [
      "kanbn-migrate"
    ];
    user = "kanbn:kanbn";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web"
      "--network=kanbn_default"
    ];
  };
  systemd.services."podman-kanbn-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-kanbn_default.service"
    ];
    requires = [
      "podman-network-kanbn_default.service"
    ];
    partOf = [
      "podman-compose-kanbn-root.target"
    ];
    wantedBy = [
      "podman-compose-kanbn-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-kanbn_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f kanbn_default";
    };
    script = ''
      podman network inspect kanbn_default || podman network create kanbn_default
    '';
    partOf = [ "podman-compose-kanbn-root.target" ];
    wantedBy = [ "podman-compose-kanbn-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-kanbn-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
