# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."kanbn-migrate" = {
    image = "ghcr.io/kanbn/kan-migrate:0.6.0";
    environmentFiles = [
      config.sops.secrets."services/kanbn/compose2nix".path
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "services/kanbn/compose2nix";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=migrate"
      "--network=kanbn_default"
    ];
  };
  systemd.services."podman-kanbn-migrate" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-kanbn_default.service"
    ];
    requires = [
      "podman-network-kanbn_default.service"
    ];
    partOf = [
      "podman-compose-kanbn-root.target"
    ];
    wantedBy = [
      "podman-compose-kanbn-root.target"
    ];
  };
  virtualisation.oci-containers.containers."kanbn-postgres" = {
    image = "postgres:15";
    environment = {
      "POSTGRES_DB" = "kanbn";
      "POSTGRES_USER" = "kanbn";
    };
    environmentFiles = [
      config.sops.secrets."services/kanbn/compose2nix".path
    ];
    volumes = [
      "kanbn_kanbn_postgres_data:/var/lib/postgresql/data:rw"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "services/kanbn/compose2nix";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U kan -d kan_db"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=kanbn_default"
    ];
  };
  systemd.services."podman-kanbn-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-kanbn_default.service"
      "podman-volume-kanbn_kanbn_postgres_data.service"
    ];
    requires = [
      "podman-network-kanbn_default.service"
      "podman-volume-kanbn_kanbn_postgres_data.service"
    ];
    partOf = [
      "podman-compose-kanbn-root.target"
    ];
    wantedBy = [
      "podman-compose-kanbn-root.target"
    ];
  };
  virtualisation.oci-containers.containers."kanbn-web" = {
    image = "ghcr.io/kanbn/kan:0.6.0";
    environmentFiles = [
      config.sops.secrets."services/kanbn/compose2nix".path
    ];
    ports = [
      "127.0.0.1:3345:3000/tcp"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "services/kanbn/compose2nix";
    };
    dependsOn = [
      "kanbn-migrate"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web"
      "--network=kanbn_default"
    ];
  };
  systemd.services."podman-kanbn-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-kanbn_default.service"
    ];
    requires = [
      "podman-network-kanbn_default.service"
    ];
    partOf = [
      "podman-compose-kanbn-root.target"
    ];
    wantedBy = [
      "podman-compose-kanbn-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-kanbn_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f kanbn_default";
    };
    script = ''
      podman network inspect kanbn_default || podman network create kanbn_default
    '';
    partOf = [ "podman-compose-kanbn-root.target" ];
    wantedBy = [ "podman-compose-kanbn-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-kanbn_kanbn_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect kanbn_kanbn_postgres_data || podman volume create kanbn_kanbn_postgres_data
    '';
    partOf = [ "podman-compose-kanbn-root.target" ];
    wantedBy = [ "podman-compose-kanbn-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-kanbn-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
