---
keys:
  hosts:
    - &node1 age1jcp58vutz6nm0q0qe5r39v2zmspjlu7ns4jfyc6fwnezgtmtrvpq7y868z
    - &node2 age1h347mrfjlsul2e7unq60xvg6dte9jcn5ge0r5q8ygcnkdzu23cfsdu6hyt
    - &node3 age1vhutk7kxakahg6hcyznvelulyqzep2023gl2hqr2pxtmgcjq4qysg0e8fv
    - &Yon age1ep4rg94wa7qgasz584jg8rddyyrcgta2fqsddc0qmlsek6wtvvgql0tnxz
    - &Kaeru age1tvwng7xyjekmc4nddvnmhu5zzrnmnryt8paa5cp6n73ak7gqzqdshysg8v
    - &Dashu1 age1jfzgcfl5hxyfdzmytgqn6dhqcf5g35775rp4597e28a3cpdktevqvzr56v
    - &Dashu2 age1y77lt4wysh733g4r0sjvc4ufz5m9e3kmvzqnj5qcptyavfrfrukq3vwkfe
creation_rules:
  - path_regex: secrets/Dashu.yaml
    key_groups:
      - age:
          - *node1
          - *node2
          - *node3
          - *Dashu1
          - *Dashu2
  - path_regex: secrets/wireguard.yaml
    key_groups:
      - age:
          - *Yon

  - path_regex: secrets/kaeru/.*
    key_groups:
      - age:
          - *Kaeru
