services:
    tailscale:
        authKey: ENC[AES256_GCM,data:Nf96pjuK4XzAo2q0pfWY9VXsNjU9Po5L119nmqaMnKc1huBl1ZgmwlzH1WQEg0UKRhZLhEmIt1a9MeryDK8=,iv:Mtk0VS2m9nlYYv5ikXp6cZOgluBJUQ/f48W1ugyvpig=,tag:TK7VXLEYfEtlJe0c4KdccQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NzdmVnlVb2VVSi9WbWI0
            TFRwUGduNllhNlhaazFuanRiS2JNUzR5RGpNCmtRcHJkSlJBWllzbHh4d1p2Nmxz
            bG1MaHRWWWpSWnVRVzNvWVA5VGM4NVkKLS0tIDNsZUowcjZFVTc4Z1doRjY5bzRM
            TVhpc2JEc1QrSGlvY0J2WnorZlM2YjAKdD9g6Mc7PLw2k7b3CJBEdF48qq9BY+jL
            rErZi2PEy8lt1jveUJ/HxDqOf167jj8+JSXpeQio8DrUK6UYVvIktQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v2764amlcmt66ehvjs84lxdturesvxeaqvcdyp62vuzvssafl3rq6yl89h
    lastmodified: "2026-07-30T11:02:48Z"
    mac: ENC[AES256_GCM,data:xvspMnEOf7ZzSc5DDEzjTClrMkTmPzF3kRhoofDMM62Wj69nl8ONTWl4XkPnRfuxZS+qDpX8E819W+pL3Q6gTNwfbS+nydcrMGfh6nmSxGdn4HefIqDf6vU8sP/jnR/e0Z9Jcva3Ff2AC881vPNPuiJBm9WlfhOTkjIVqP72zSw=,iv:C7uHJz4xYcfwtXa5qSE7bdl4hutMKBc/PWfTDKaRwzk=,tag:iJj398GRYDtbOkrud7kC3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
