services:
    tailscale:
        authKey: ENC[AES256_GCM,data:WzGCfuPU/2+Uo3rQis1L+Bs9GQugLNaFKHw2A01s2Gqd87001+ZVeMLf4GDTjIFaOyE6iZLX0cFy/CFJsZg=,iv:L84Po44FK7oWE0/YOUHcZPjOEfx45sUv8VwT7NHq/Vk=,tag:XCWU7H7K8C+nP4mS4R3LNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NzdmVnlVb2VVSi9WbWI0
            TFRwUGduNllhNlhaazFuanRiS2JNUzR5RGpNCmtRcHJkSlJBWllzbHh4d1p2Nmxz
            bG1MaHRWWWpSWnVRVzNvWVA5VGM4NVkKLS0tIDNsZUowcjZFVTc4Z1doRjY5bzRM
            TVhpc2JEc1QrSGlvY0J2WnorZlM2YjAKdD9g6Mc7PLw2k7b3CJBEdF48qq9BY+jL
            rErZi2PEy8lt1jveUJ/HxDqOf167jj8+JSXpeQio8DrUK6UYVvIktQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v2764amlcmt66ehvjs84lxdturesvxeaqvcdyp62vuzvssafl3rq6yl89h
    lastmodified: "2026-08-01T14:25:43Z"
    mac: ENC[AES256_GCM,data:fLyKxfNzTQArKgQzy6bWakYIobDMnOHGhCAbTk44JjtyuYWt7xfvbWVgOzrxKkcdl88aaXxyj6hizPVsKD/p5hkJbUMrXZ2RiIgHd0JB6JpwGwUVwgYcFZxcIQfl3S7CKGbjitWqqiApP+Jao3+6l9qIdj5vzQgAv2u4SF7xlP0=,iv:9SCGJKFL+aH5PX31aX5YCr3PV320g0jUQKRcrFLIkw8=,tag:s6Ljfl5BWQBffoLoUbigWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
