services:
    tailscale:
        authKey: ENC[AES256_GCM,data:7n6pP9+Jc6OAzeUocXrDgxUwgb4WWEU+fXkmcd+s2M6FdcjEPq9AJDiIIEUwZrr8cysdCokwK2D0ydD2lkY=,iv:GH+VPFnnMYLnTwWlYiKHoD5jEUCbQ4ieTDxmUYcK9IA=,tag:Aq58zFJN+yhSoLz+OeqUgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOEpQb3VUdU9qNjltQnZJ
            bEtUR3YzMm5GTmduTnVHMGtldEdLS1c4aUdnClArS2RRODFtNStYaHVCenNCWWNG
            MHIvVSswQllab3d2czNmTms5ZktSR00KLS0tIC9UZ2tuVWtzMXNUMm9SZFpsU2xm
            cUFoUk41ZGlSbXl4YkE2ZFowZkQ4VGsKbhkj3CxapkD2TIK6CjOL+dhzXFSeQ1lz
            Iwp1WAQ1m0iRu0XK0lrvhf7WIR9j3YLsuuG3UX6qVY/VIm3FazGuyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19qputpwf6cnptj7emvyk4lhr22m5mp0f070hlk49zttka8rhd46qjdlvk7
    lastmodified: "2026-08-01T14:26:00Z"
    mac: ENC[AES256_GCM,data:Ytzve+fMjkia4DiYzDx8XmNPAUIOaTZx2h/uEbvL8lKq8Rsw4gbTd/T1xDEhFs3uIi4Ft0o+u1PjSW5sJFmPr9qW5By6orK83f49PS7KX8Cg7/Ze75yfVtbFDsFogigi3kjfNWG5vhQR1cROALqqY1iKzU15QjC1kvnSlo3adSk=,iv:r6CcdIujuWHJj65kYBMrZ9vHFNPpCibjaCSVZshJIBo=,tag:m62jluZdMnLhT8GPGKDOLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
