services:
    tailscale:
        authKey: ENC[AES256_GCM,data:w9p4GcinVxay+SCOmY4w/PetgcLVmmcwmWrEvRVmOvT0NmfqNw8qT0KtJoc8ZtQMpxwLBe4n82UcYayeQGA=,iv:n3bDr4bKuTR5HIbprHhj7ZeSDqIJ7ejtrvMzk5dUJkE=,tag:IaDQemCyWOdjolt8Yf9DBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOEpQb3VUdU9qNjltQnZJ
            bEtUR3YzMm5GTmduTnVHMGtldEdLS1c4aUdnClArS2RRODFtNStYaHVCenNCWWNG
            MHIvVSswQllab3d2czNmTms5ZktSR00KLS0tIC9UZ2tuVWtzMXNUMm9SZFpsU2xm
            cUFoUk41ZGlSbXl4YkE2ZFowZkQ4VGsKbhkj3CxapkD2TIK6CjOL+dhzXFSeQ1lz
            Iwp1WAQ1m0iRu0XK0lrvhf7WIR9j3YLsuuG3UX6qVY/VIm3FazGuyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19qputpwf6cnptj7emvyk4lhr22m5mp0f070hlk49zttka8rhd46qjdlvk7
    lastmodified: "2026-07-30T11:03:45Z"
    mac: ENC[AES256_GCM,data:rkuRq7VVHTIWjEoG1RjJ3SReZVPH0ZLPBnkLMksMhjrfFKbuKowtZaBJz0w8O1V6RZOcuVb+VVfd97HEkdDfOEQfzNt4MCufVwn0gpdX6yOjallVWjhWjlecI4TlRH8/8T/amUN4D4ZBMbmyzLHd3I0kHqstN8Ohf/yb48uda64=,iv:vHMm/pbElhdTU7kSXEIr9P3ZBAxm+si7TyTutk2dXVM=,tag:HlZmPAHFEHuygSbPQiRrlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
