services:
    nextcloud:
        adminpass: ENC[AES256_GCM,data:Wk6KZWYQuEM=,iv:Fvky2bVZtZC7U7fqPkv0+8zYcyHl8tvpSvssdViLexc=,tag:oMiXwWlHdEGRiSz6vEfUQw==,type:str]
sops:
    age:
        - recipient: age1tvwng7xyjekmc4nddvnmhu5zzrnmnryt8paa5cp6n73ak7gqzqdshysg8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc09HSXJLNnVrWEcwMmZF
            V0Y3a05zcGswUVR5WkJ2MDlZTEtKQy9SMnlNCnhLNWNxNldOWUZ6aWtRMjRqQ1k1
            SjlzeUlxT3pVMWtqcldCY0NtOHM2Mm8KLS0tIE94OEVkR2FoWnFWZnphYStmY1VD
            T0RqeXhhdUZla21ORzEzSFBlWjNzL3MKkCtbcFDEJiMnLAE3RYXkXFXas+Ot3sbF
            lK4XYAWtKDwdWeYPpIgDGOW/IVIBhq7OtZHbEJSSfucdm9wfWlsWQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T16:26:51Z"
    mac: ENC[AES256_GCM,data:8uDlgpTemjE2/js8bAkdovYxwzkwdbGgtgVXL4DGBq+7aHWVLhtW8TjdWqs1Rk9u9X+9tO72lp2djkxla23t727rmSOSfRF9wuYE0zVUUrLbwgyRHXomW2dLqXYF9ow+cdZ0M3V90Ds6SkzN43MNyEbLHzmeB/AxF8F/R4FdJj4=,iv:AI9j3BQQKSj2zgQShhj/QIzLvgpHx0BosDfZLhEtNJA=,tag:QKh9woVCAiyL3zmOBFJwlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
