services:
    nextcloud:
        adminpass: ENC[AES256_GCM,data:Wk6KZWYQuEM=,iv:Fvky2bVZtZC7U7fqPkv0+8zYcyHl8tvpSvssdViLexc=,tag:oMiXwWlHdEGRiSz6vEfUQw==,type:str]
    caddy:
        cloudflare_dns_api_token: ENC[AES256_GCM,data:bXbF0O6oq4m5tWGWMHp2tZk/KB76OHR3YtjqurwdmzdCJyxkCc1OAGf2ahLQVVgPlmBAYh+0Fi5Y98wGMFrII/w=,iv:asC90W5QqK+oewDCLjH4kaj4n14eqQoDjL49zSQO3fA=,tag:qTfmbI4c0loNlwkPyHDDXg==,type:str]
    authentik:
        env: ENC[AES256_GCM,data:F11mZl5dv0ZuXtb9lUctj1fmVFKU01MepoArYua95heCEScqFKSZzk347KnvrI5wPNbZBEBpk13rc7rCeL5Er551yN8ejvvdx9XLRUHmHlB8LmXbb4A+3w1AEY/hOAeOVEh3iCSxxPp7AbHGFdYG9g9mfC84pOk9E3iqYRKivDOjrH/Rczcb/P4Q5Fj6cOXxIN7ZG7k/szvkuIE/9nJxl0SW/w==,iv:mdDwvYkDY2qO+ecpIwtNlrUGFA1JePFblw1ItPyaNZA=,tag:tJYrOt3co7i2S9AA+/aqFw==,type:str]
sops:
    age:
        - recipient: age1tvwng7xyjekmc4nddvnmhu5zzrnmnryt8paa5cp6n73ak7gqzqdshysg8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc09HSXJLNnVrWEcwMmZF
            V0Y3a05zcGswUVR5WkJ2MDlZTEtKQy9SMnlNCnhLNWNxNldOWUZ6aWtRMjRqQ1k1
            SjlzeUlxT3pVMWtqcldCY0NtOHM2Mm8KLS0tIE94OEVkR2FoWnFWZnphYStmY1VD
            T0RqeXhhdUZla21ORzEzSFBlWjNzL3MKkCtbcFDEJiMnLAE3RYXkXFXas+Ot3sbF
            lK4XYAWtKDwdWeYPpIgDGOW/IVIBhq7OtZHbEJSSfucdm9wfWlsWQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T09:32:47Z"
    mac: ENC[AES256_GCM,data:vUZjcLd/N5ADXwmSebXp2zYjuJeGtNBgNgSpKnlwoXTjrzda+dKo35ec77ag3tnlVAiuMclldOtZz2hm7uTGECdEv/e9ODP/W1I3UvDK7Lhs55GwF389Tzz2PeRdp6SpAy/ztrXdCat3HZk5Ag3T3RCPJsK3i+FRdxFqISWDInk=,iv:Rz50IeVBQS7DfDKbZMdTQ5K/KfBtEYPPFYQnSDTUG7o=,tag:7soGoois4WngNohOonwgyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
