services:
    caddy:
        cloudflare_dns_api_token: ENC[AES256_GCM,data:mEDWOvzJCHY1YzKELCarmvGRrPTzHYp2AbHjqze/YfBnutinhCAiGUX8ziIZRAYU2ImiwDngmZth0FNjhw10XS4naeBZnnUB+D+XMOdWdQ==,iv:i/vY+7ZjRXFULvHgCl+1bqhPebbnqnzHP+WyqfmXY6I=,tag:y2p119yhYFLaZxDEI+pCDw==,type:str]
    vaultwarden:
        admin_token: ENC[AES256_GCM,data:cfkPCvIaQvlxkPha8ZKU/CvvLVc8/Q9U5PKpqWwhr9BuNycBlglT8PRty7ZO9A2vHL8vI8HIrftRhIeGM0RohpMEgtRVlefUYMn0cIOUaYjSMZMJtYKv4+RPsN15ycf14mPqTplpXZMvK6FEgAsTjVakRlZQomc1n3/jld9lu2xbuQBkL64fboyku75FCvsyTFibLCunRRFUxwiOElBgkxhLqFzfG4GRqDGhLnzoYr9HY9maZLrjxX6BdQCulVg5Nfr3NP6HGqqlf/oo9XpdJ07O6CrSgN9+JktY5Lm7Bq9SoAFELih1tBVFUdV2SGyTu7CtPeunHOp6bTUT/tRFgYat83vBrblPsOLKKNRpsDdcwU6J72NSqpZ6/Mv1kIWWW7koIjpRhd+BI0wmufeYbQs0mWaIvmX4LE1J2D1TpBhobNizEvBkmAq2Tlp+Qjk3w5xa/UvuJ0Ps/Pc7w2RKVux2MsWCqcngztWZzKfqVZD77wzFnxnc2NBZKlPNf7FEVdKl/x9kk7HmDuegPnlgDp7qpw==,iv:HuXZZTUdGbft4Yi+3lo4nx2RvHv+zdJZk6lKwYZxl+w=,tag:kL3HwLRPA0RtbUCDDqHlpQ==,type:str]
    nextcloud:
        admin_pass: ENC[AES256_GCM,data:kSqFx6DVA5R74NfJr5kWpws4V5hB59EmNw==,iv:T+hPPQeLMtkC3FIhvMBVm3Mql97YLueybCVmVBpX0LI=,tag:7evhCB+16PEujyzWmw7FeA==,type:str]
        ldap_pass: ENC[AES256_GCM,data:1zPkle6Gf1E/UJ/4D3Yj4kHGaDdelZIzdjpPmjZwo5uXDwiBAsmewZwBktL1Ekl/dzVQm3ZED0mOu548,iv:7978E/P5YkJ2cBcM1/kdnpG0ch/IAtGSz64idvBAi40=,tag:9cg6fN5uvc6P30cN6+eB1A==,type:str]
    authentik:
        core: ENC[AES256_GCM,data:n4J/DOoyXhX+8TN3E0NjybEil8kKkWKKLwNvBpkjJgy4IfW5iWdCQSxCp741FnGgAMTv2x21phxWvlFAcybbJuLM9leO74iRroltuQxSuFz26bzJwHaw2qLC2LGoMyQjXDn8ZZnpMQD6j59wcztoo0s9I2xUkLtbbu5unoZOroXTbmTcIkEUWrOq20sFb7nzHAX1vk8K57BkMYwotpHl+ytbno8w1STgBVChEMZ1ZJg4xU424XWUxbdpPOvsxdVQRCwz6qgWWTANnt/jD0vl8kttfpVFaVyhZf4ACkOxfUOOTZOOGJ/6eKXxzNcwUCSdmnYE+CuSmD5FebPFibmOf1c37cO2pl8tPes/h8RKt1Hl/y9dy4XG6wH2yfYu/N3+GMRJRRXuSSQVSdDAhNWXvWvh0IcPEUs9b6wbpBMTdNxLo42gkhXPfAw7+6XF87xSdpkv7eqKboZsIseel5t/PI3uVzUTpzN1UvtcKuQheVgSi/rMZtnZOdgHO5u7xmQ=,iv:XrMPXiFVoYqA/G5PfRkxF+jp4Q/aX6eI125hiM9DoI0=,tag:rGVnF5W/RBxUlJiFODIb6A==,type:str]
        ldap: ENC[AES256_GCM,data:z5GBx92aBwHRMHOSELmOm3alxte0mbuDpivQiRjey4bS5NFJpXPKemXWg2cksjYvDT8CSpFRcYSpi/qrwhJgJEAxt2ovgEZVE97ti8VSpg==,iv:XEeYfGOHnplRrU+M2xGpEpwH0vNYN0Xt+bazusMly9o=,tag:oNbY3hU9wOFDYGja/76ApA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZERtMTRRTExid3JsUHoy
            MHh1M1VjWlNsdGJOY2RNcFlhZWE3RHY4Nmo0CmRDMjRpYTkvQkZrUGhKb3ZZaVJv
            R3hzanJsRWRudklrUHhvb1h6RkpWWTAKLS0tIGhlb2l0Z3R1VW5Ub3d4RFpLVUVz
            RHJYWmh1aGJCWUczQmQzVklXZDlISEEKmBRZC/TUoSxYZbhYCEJu+KJg8oCKjd0P
            6eaaTyePe3QzNYak3HIhk6x/10mM0//a88q/INzoIz/rwCvbcDOpPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yhfdp6klh4gwpcmnjd5h0dfdkw6s0xn6s7dzc59wf468zk4zmcpq6cudu9
    lastmodified: "2026-06-06T14:30:17Z"
    mac: ENC[AES256_GCM,data:sa6AybNglYwahsRXcB4VwGW0bTZxszSfUJV2iQPUO7w+wvgg3e5R/cPwvJ0abdvUdhhFkT2IB9dR1y4bC3o9xiXpIYO6DzkF+h+x8o9C6zuqQijFq3QDVDAqYJxXfN1wOLGIrUFOyJrXCtY6Efu22A0Nyn+uBoWyQfHyTSvknrk=,iv:8MIDJXrNW68arryy4gxH8fYAWfEqbN2kg1n0Bhaahhg=,tag:F0Ffdp7ywQBtY/lySvnclw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
