services:
    nextcloud:
        adminpass: ENC[AES256_GCM,data:Wk6KZWYQuEM=,iv:Fvky2bVZtZC7U7fqPkv0+8zYcyHl8tvpSvssdViLexc=,tag:oMiXwWlHdEGRiSz6vEfUQw==,type:str]
    caddy:
        cloudflare_dns_api_token: ENC[AES256_GCM,data:bXbF0O6oq4m5tWGWMHp2tZk/KB76OHR3YtjqurwdmzdCJyxkCc1OAGf2ahLQVVgPlmBAYh+0Fi5Y98wGMFrII/w=,iv:asC90W5QqK+oewDCLjH4kaj4n14eqQoDjL49zSQO3fA=,tag:qTfmbI4c0loNlwkPyHDDXg==,type:str]
    authentik:
        env: ENC[AES256_GCM,data:F11mZl5dv0ZuXtb9lUctj1fmVFKU01MepoArYua95heCEScqFKSZzk347KnvrI5wPNbZBEBpk13rc7rCeL5Er551yN8ejvvdx9XLRUHmHlB8LmXbb4A+3w1AEY/hOAeOVEh3iCSxxPp7AbHGFdYG9g9mfC84pOk9E3iqYRKivDOjrH/Rczcb/P4Q5Fj6cOXxIN7ZG7k/szvkuIE/9nJxl0SW/w==,iv:mdDwvYkDY2qO+ecpIwtNlrUGFA1JePFblw1ItPyaNZA=,tag:tJYrOt3co7i2S9AA+/aqFw==,type:str]
compose:
    proxy: ENC[AES256_GCM,data:vIJ9yPqwBZqX08JrTBoMu0ssKf4KeEJxMGSvyN8Q0fR9/LYISu0IXNWGaIVyNb5T9TDjg/5jHDoJVjXJreGs0JqmHTF6af/rO9Sh9IId1IPrDRvppGCfPP7MOR8/+6pzcNQPTo8SBMRnK7t4CQ==,iv:bNWBmsA7I8hhGjNZ+GEo+X5/DN1Jck5nuOEhAG7MuTE=,tag:FhJJkCwiUDH+0UoMRyCdSQ==,type:str]
sops:
    age:
        - recipient: age1tvwng7xyjekmc4nddvnmhu5zzrnmnryt8paa5cp6n73ak7gqzqdshysg8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc09HSXJLNnVrWEcwMmZF
            V0Y3a05zcGswUVR5WkJ2MDlZTEtKQy9SMnlNCnhLNWNxNldOWUZ6aWtRMjRqQ1k1
            SjlzeUlxT3pVMWtqcldCY0NtOHM2Mm8KLS0tIE94OEVkR2FoWnFWZnphYStmY1VD
            T0RqeXhhdUZla21ORzEzSFBlWjNzL3MKkCtbcFDEJiMnLAE3RYXkXFXas+Ot3sbF
            lK4XYAWtKDwdWeYPpIgDGOW/IVIBhq7OtZHbEJSSfucdm9wfWlsWQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T07:59:59Z"
    mac: ENC[AES256_GCM,data:C+ByDBqgSDfoQovfzo4vv/tIwYTJGIAbuO2DFQS2MOc3JrVE2SvkCFAG4vNznRUb+yObI30lo7g8TX6WNGkgJzsY2eSjfJgkpL7Pt4O4Xc26R4F2vbJ0naTb4OZj9uW6BTWSNStIbm+2ttJEbjxehZv02Knv67mSkODlflKKMFk=,iv:n0NRq6f81KLo8xZRZtHRnFqbC7hQ1A8XouUUCRCZ9SM=,tag:z3UpqzjPq6AnXMpheWwv5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
