services:
    caddy:
        cloudflare_dns_api_token: ENC[AES256_GCM,data:mEDWOvzJCHY1YzKELCarmvGRrPTzHYp2AbHjqze/YfBnutinhCAiGUX8ziIZRAYU2ImiwDngmZth0FNjhw10XS4naeBZnnUB+D+XMOdWdQ==,iv:i/vY+7ZjRXFULvHgCl+1bqhPebbnqnzHP+WyqfmXY6I=,tag:y2p119yhYFLaZxDEI+pCDw==,type:str]
sops:
    age:
        - recipient: age1yhfdp6klh4gwpcmnjd5h0dfdkw6s0xn6s7dzc59wf468zk4zmcpq6cudu9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZERtMTRRTExid3JsUHoy
            MHh1M1VjWlNsdGJOY2RNcFlhZWE3RHY4Nmo0CmRDMjRpYTkvQkZrUGhKb3ZZaVJv
            R3hzanJsRWRudklrUHhvb1h6RkpWWTAKLS0tIGhlb2l0Z3R1VW5Ub3d4RFpLVUVz
            RHJYWmh1aGJCWUczQmQzVklXZDlISEEKmBRZC/TUoSxYZbhYCEJu+KJg8oCKjd0P
            6eaaTyePe3QzNYak3HIhk6x/10mM0//a88q/INzoIz/rwCvbcDOpPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T09:55:36Z"
    mac: ENC[AES256_GCM,data:WUq9IFl5lOnYhGLXumWkjkaEFN5I94eEYhtgeOCFASe7b1XiLyQPMIYMzHQ4sM2VGi2uG9SPForv9wtYKH1MoOE3vuc5btxF5NtcdKS1lUqgHnA3blu/PMp2QSg0/qxTncF4fzZ+mdWI72QUKGAMrgFklsFzsYcSMfa61O9EKMo=,iv:4ICkciH2kflb7VAH0BDgeFugvePVcZZnBvqGR93xDoI=,tag:87h57MGhXHrTZtIQlVrN8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
