services:
    nextcloud:
        adminpass: ENC[AES256_GCM,data:Wk6KZWYQuEM=,iv:Fvky2bVZtZC7U7fqPkv0+8zYcyHl8tvpSvssdViLexc=,tag:oMiXwWlHdEGRiSz6vEfUQw==,type:str]
    caddy:
        cloudflare_dns_api_token: ENC[AES256_GCM,data:bXbF0O6oq4m5tWGWMHp2tZk/KB76OHR3YtjqurwdmzdCJyxkCc1OAGf2ahLQVVgPlmBAYh+0Fi5Y98wGMFrII/w=,iv:asC90W5QqK+oewDCLjH4kaj4n14eqQoDjL49zSQO3fA=,tag:qTfmbI4c0loNlwkPyHDDXg==,type:str]
sops:
    age:
        - recipient: age1tvwng7xyjekmc4nddvnmhu5zzrnmnryt8paa5cp6n73ak7gqzqdshysg8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc09HSXJLNnVrWEcwMmZF
            V0Y3a05zcGswUVR5WkJ2MDlZTEtKQy9SMnlNCnhLNWNxNldOWUZ6aWtRMjRqQ1k1
            SjlzeUlxT3pVMWtqcldCY0NtOHM2Mm8KLS0tIE94OEVkR2FoWnFWZnphYStmY1VD
            T0RqeXhhdUZla21ORzEzSFBlWjNzL3MKkCtbcFDEJiMnLAE3RYXkXFXas+Ot3sbF
            lK4XYAWtKDwdWeYPpIgDGOW/IVIBhq7OtZHbEJSSfucdm9wfWlsWQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:25:45Z"
    mac: ENC[AES256_GCM,data:bjU3lQj83FH16U2WTVEe/mC9hKPveuY6yPbHps7iTJHFPMVkBQ8zbtemAR4u2r84G2msq+wAPBXjRn8w8ulvyIj91Q0pNGTA6sZBR9/pRYl0vXTn81MnN/CwOaqXiBdyc7S/VOlIyaITucKRmrOQO+56Nld9V72zMOwuM6FW+GE=,iv:z6gIdjfY3JfYWJmdko5B3N8etSO/Sb5r9CRZ4bYH/2s=,tag:Z/P5QClT/MfSN+tHyVVRfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
