services:
    tailscale:
        authKey: ENC[AES256_GCM,data:1jUu8f8Qd8/BQPRb0cX4rKTTthWVCE7qoYTirCctmKetNkehIyiSTabDfvtx+Gv67uzO4lT8jGy+J9R/sF4=,iv:YhArW0apbP1rB/+uL7oGCEYvgQWkoboth8381BYqLK0=,tag:FHy7KGHGvNlKdzAvcOkqXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVHRGd09Bbm9MMzFUdEF2
            ZzRWUElGTjNqREdYaC8xY2lsWThuQlBmWEdRCndNZFo0MDIxd1FrQVphOWF1R1oy
            NWZmNUsvTFZjNEV3MFBMcSsrY0NGM0UKLS0tIFo3L2lLNCtYSWpkdG1QUjVMRGwv
            TE9MZmhzbTNZdXpjeU5Gay9sNjIzdlkKVzOCRjkzZ8a7MbTwQ29CFJcR6HHJM6Y4
            /u2bGID5n9wtTFyJU91fAE5/0ReZ2bJQszUw/YkDfBvkyU/i9Dd5PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132zjthznrrjejt2kawgmu3cj33jt65vv0c5tg7vshknnshucrylsdaty4t
    lastmodified: "2026-10-09T11:09:04Z"
    mac: ENC[AES256_GCM,data:5pgam0qcKP7I1uX9VRdSI4IUZP2ppPJs16jFIVYIVTNddP+n4FDegT2oT6Fpkz8mH6BY+QB84mqykoDFT8mKVZuJRqLrjLP+YIhe+VVxnLwlyD/pHrFRPJjR4/CFjcsLdPpszRRG7E9Vpt61OleflfEDVRmSxg5EP5F7/MycB7s=,iv:T5rvbokyFJzmsw5dqyxCuSCkZAw/96VtBbUkTvWWNuY=,tag:bFJXq8LsoU8rOP1PpQ61ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
