services:
    syncoid:
        sshKey: ENC[AES256_GCM,data:Sfchimhjti3USe6hxLUGzhjmzqmUXoAlB2LnSGgpOn1fcHP5l1OIlwL4Vkat4ieKxxZx9wvpVH+oaRe37TiEuA2fu7b/ZdWXdng9/vVAYjaagQZWcziHFeuugJRXQrnb8GvpgwSwjS9ffjZkCsSVodqpyz0iCA1MQlo2G9c1rlLvObeUVDaPTdui3qm8rzAnCn6uarItQIupzGSHj2HBxt+2OFo8wbOtDCkAl+/Sy0EXPbAAwBxwZf0g07Zb+TghBUEzK9omTMa5j400GtiHxmW6XJyjpv9Ux0XhMyReSc0U4DVqw4kR+FgjB17yIh4tS2hgvbf1ZuB0huWAkMLwh75lgMCT9SsYq70kfFsNA0lnfQuwnQt9I8PMgPKuMvz5zhfkyW0Fn4kSXjTLdOigL4LloRpVzlI8L3GPNq5+8nx9iJlRxrZZMzqQwQ3XoylHNPK7KyZIYGTI2X90RK5V7m1ZGPCV0DbZW3mv6U5TiG4WEX0or3O6BWqBMRQU623wUcer,iv:ztNaqwfKOmwrXPAXuM0wJqkp1fvWx5/qYkydwRfLHRU=,tag:Wr8MP4OGmoWF/MsMVsytqA==,type:str]
    tailscale:
        authKey: ENC[AES256_GCM,data:1jUu8f8Qd8/BQPRb0cX4rKTTthWVCE7qoYTirCctmKetNkehIyiSTabDfvtx+Gv67uzO4lT8jGy+J9R/sF4=,iv:YhArW0apbP1rB/+uL7oGCEYvgQWkoboth8381BYqLK0=,tag:FHy7KGHGvNlKdzAvcOkqXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WWpPUGM0YVFqQ3Ezdi9u
            dEQway9HTkxlaXExWDNtK1RBUEdSMVdRZ2hBCnZobVRJMEM5NFRZbDloOTA3dnlj
            RVZGb2YrczlWbUdRS1NuRE5hREVOckkKLS0tIEI2dVJibzBxQ3M2ak5LOW5jT05H
            N0tpKzREdnZwRDZCL3BhQ0VEQytmM1EKTnDXhfl3kx1WAopppSaz++DFESPdTZTk
            yMck7krDl/rqk+ih+CX37OVHk+8yFIevzGJSNMvhL0AP2qRw6cgLNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10gj4zqgnh7ejxhmwn22ft5adzmm7h5zewf05jhm899cdt264pvfskn7kq9
    lastmodified: "2026-10-09T16:44:47Z"
    mac: ENC[AES256_GCM,data:mqtsc6sJZR4mdHhJ4E4KC6z89yspvHEmNIQqfnKrfZhmJjRzZCJBrvTfRGbGGs//PK0DLuQHLc49LfZoDBpwrMko7dnik88NfVAU6NEnTDwVg1wO8u5hQUMIaup7s9BPDK26mipuj9DGkxc2BDpGCkTiXQZdC0P89hHc5KFFWhs=,iv:VroWJidRW1zfJ2K5y4lD2BUfm1BwQMLk2EEGEGE/X0A=,tag:1ZYEzskKun3kANgPgglTzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
