services:
    tailscale:
        authKey: ENC[AES256_GCM,data:1jUu8f8Qd8/BQPRb0cX4rKTTthWVCE7qoYTirCctmKetNkehIyiSTabDfvtx+Gv67uzO4lT8jGy+J9R/sF4=,iv:YhArW0apbP1rB/+uL7oGCEYvgQWkoboth8381BYqLK0=,tag:FHy7KGHGvNlKdzAvcOkqXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WWpPUGM0YVFqQ3Ezdi9u
            dEQway9HTkxlaXExWDNtK1RBUEdSMVdRZ2hBCnZobVRJMEM5NFRZbDloOTA3dnlj
            RVZGb2YrczlWbUdRS1NuRE5hREVOckkKLS0tIEI2dVJibzBxQ3M2ak5LOW5jT05H
            N0tpKzREdnZwRDZCL3BhQ0VEQytmM1EKTnDXhfl3kx1WAopppSaz++DFESPdTZTk
            yMck7krDl/rqk+ih+CX37OVHk+8yFIevzGJSNMvhL0AP2qRw6cgLNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10gj4zqgnh7ejxhmwn22ft5adzmm7h5zewf05jhm899cdt264pvfskn7kq9
    lastmodified: "2026-10-09T11:09:04Z"
    mac: ENC[AES256_GCM,data:5pgam0qcKP7I1uX9VRdSI4IUZP2ppPJs16jFIVYIVTNddP+n4FDegT2oT6Fpkz8mH6BY+QB84mqykoDFT8mKVZuJRqLrjLP+YIhe+VVxnLwlyD/pHrFRPJjR4/CFjcsLdPpszRRG7E9Vpt61OleflfEDVRmSxg5EP5F7/MycB7s=,iv:T5rvbokyFJzmsw5dqyxCuSCkZAw/96VtBbUkTvWWNuY=,tag:bFJXq8LsoU8rOP1PpQ61ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
