# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
      systemd.network.enable = true;
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    zfs.extraPools = [ "kaeru" ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0367b63d-3957-4266-88a5-f1a82dc504ef";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/B8BC-B747";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/nix/store" = {
      device = "/dev/disk/by-uuid/0367b63d-3957-4266-88a5-f1a82dc504ef";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

    "/var/lib/containers" = {
      device = "/dev/disk/by-uuid/0367b63d-3957-4266-88a5-f1a82dc504ef";
      fsType = "btrfs";
      options = [ "subvol=@container" ];
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
