# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."handbrake-handbrake" = {
    image = "docker.io/zocker160/handbrake-nvenc:latest";
    environment = {
      "GROUP_ID" = "100";
      "NVIDIA_DRIVER_CAPABILITIES" = "all";
      "NVIDIA_VISIBLE_DEVICES" = "GPU-b2f09e13-5cf1-0138-aa8b-7d04ac327bb6";
      "TZ" = "Europe/Berlin";
      "USER_ID" = "99";
    };
    volumes = [
      "/srv/media/handbrake/output:/output:rw"
      "/srv/media/handbrake/storage:/storage:ro"
      "/srv/media/handbrake/watch:/watch:rw"
      "/var/lib/handbrake/config:/config:rw"
    ];
    ports = [
      "127.0.0.1:5800:5800/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=handbrake"
      "--network=handbrake_default"
    ];
  };
  systemd.services."podman-handbrake-handbrake" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    unitConfig.Description = "Container handbrake-handbrake generated by compose2nix.";
    after = [
      "podman-network-handbrake_default.service"
    ];
    requires = [
      "podman-network-handbrake_default.service"
    ];
    partOf = [
      "podman-compose-handbrake-root.target"
    ];
    wantedBy = [
      "podman-compose-handbrake-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-handbrake_default" = {
    unitConfig.Description = "Network handbrake_default generated by compose2nix.";
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f handbrake_default";
    };
    script = ''
      podman network inspect handbrake_default || podman network create handbrake_default
    '';
    partOf = [ "podman-compose-handbrake-root.target" ];
    wantedBy = [ "podman-compose-handbrake-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-handbrake-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
