name: "Build"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: Svenum/attic-builder@main
        with:
          build_systems: true
          build_packages: true
          attic_url: https://attic.holypenguin.net/
          attic_cache: holynix
          attic_token: ${{ secrets.ATTIC_TOKEN }}
